### ISSUE TITLE
Epic: Cosmos+Tendermint IPLD integration

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-codec-dagcosmos#42]
Creating this top-level issue to help track the remaining tasks

- [x] IPLD schema spec
- [ ] Register new multicodec types
- [x] Tendermint types code gen https://github.com/vulcanize/go-codec-dagcosmos/issues/1
- [x] Cosmos types code gen https://github.com/vulcanize/go-codec-dagcosmos/issues/1
- [x] Basic Tendermint marshallers and unmarshallers
- [x] Basic Cosmos marshallers and unmarshallers
- [ ] HeaderFieldTree and BlockPartTree support
- [ ] Testing
- [ ] Custom node interface implementation (optional, nice to have)
